fixes Sass::UnitConversionError
* generate via foundation's rem-calc() instead of hard-coding to pixels
to avoid a SASS compilation error.

    ActionView::Template::Error:
           Incompatible units: 'rem' and 'px'.